'use client';

import { CheckCircle, WarningCircle } from '@phosphor-icons/react';
import type { BulkImportRpcResult } from '@/types/bulkTimetableImport';

interface BulkTimetableResultProps {
  kind: 'success' | 'failed';
  /** Present only on success — the exact `BulkImportRpcResult` from RPC 114. */
  result?: BulkImportRpcResult | null;
  /** Present only on failure — the friendly error message. */
  error?: string | null;
  /** Success-only action (back to the timetable list). */
  onBackToTimetable?: () => void;
  onImportAnother: () => void;
  onRetry?: () => void;
}

function StatLine({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-xl border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-800/50">
      <p className="text-[11px] font-medium uppercase tracking-wider text-gray-500 dark:text-gray-400">
        {label}
      </p>
      <p className="mt-0.5 text-lg font-bold text-gray-900 dark:text-gray-100">{value}</p>
    </div>
  );
}

/**
 * End-state panel for the bulk import workflow. Success shows ONLY the
 * numbers returned by the atomic RPC; failure shows the friendly error and
 * never fabricates row-level details the RPC did not return.
 */
export function BulkTimetableResult({
  kind,
  result,
  error,
  onBackToTimetable,
  onImportAnother,
  onRetry,
}: BulkTimetableResultProps) {
  if (kind === 'success') {
    return (
      <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 dark:border-emerald-900/50 dark:bg-emerald-950/30">
        <div className="flex items-center gap-3">
          <CheckCircle size={28} className="text-emerald-600 dark:text-emerald-400" aria-hidden="true" />
          <div>
            <h2 className="text-lg font-semibold text-emerald-900 dark:text-emerald-200">
              Import Successful
            </h2>
            <p className="text-sm text-emerald-700 dark:text-emerald-400">
              The timetable and lesson plans have been imported. Live classes will be generated by
              the scheduled materialization.
            </p>
          </div>
        </div>
        <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          <StatLine label="Slots Created" value={result?.slotsCreated ?? 0} />
          <StatLine label="Slots Reused" value={result?.slotsReused ?? 0} />
          <StatLine label="Slots Extended" value={result?.slotsExtended ?? 0} />
          <StatLine label="Lessons Created" value={result?.plansCreated ?? 0} />
          <StatLine label="Lessons Updated" value={result?.plansUpdated ?? 0} />
        </div>
        <div className="mt-5 flex flex-wrap gap-3">
          {onBackToTimetable && (
            <button
              type="button"
              onClick={onBackToTimetable}
              className="inline-flex items-center rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-blue-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
            >
              Back to Timetable
            </button>
          )}
          <button
            type="button"
            onClick={onImportAnother}
            className="inline-flex items-center rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-800"
          >
            Import Another File
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-red-200 bg-red-50 p-6 dark:border-red-900/50 dark:bg-red-950/30">
      <div className="flex items-center gap-3">
        <WarningCircle size={28} className="text-red-600 dark:text-red-400" aria-hidden="true" />
        <div>
          <h2 className="text-lg font-semibold text-red-900 dark:text-red-200">Import Failed</h2>
          <p className="text-sm text-red-700 dark:text-red-400">{error ?? 'The import could not be completed.'}</p>
        </div>
      </div>
      <p className="mt-3 text-sm text-red-700 dark:text-red-400">
        No changes were applied — the import is all-or-nothing. Your preview is still available
        below so you can review the file before retrying.
      </p>
      <div className="mt-5 flex flex-wrap gap-3">
        {onRetry && (
          <button
            type="button"
            onClick={onRetry}
            className="inline-flex items-center rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 focus-visible:ring-offset-2"
          >
            Retry Import
          </button>
        )}
        <button
          type="button"
          onClick={onImportAnother}
          className="inline-flex items-center rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-800"
        >
          Choose Another File
        </button>
      </div>
    </div>
  );
}
