-- ════════════════════════════════════════════════════════════════════════════
-- MIGRATION 114 — Bulk Timetable + Lesson Plan Import
-- ════════════════════════════════════════════════════════════════════════════
-- Purpose
-- ───────
-- Server-side atomic bulk import used by the (future) one-file Excel/CSV
-- importer. The frontend parses + validates the file, shows a preview, and on
-- admin confirmation sends NORMALIZED ID payloads to this RPC:
--
--   p_slots: [ { key, teacher_id, batch_subject_id, day_of_week,
--                start_time, end_time, valid_from, valid_until } ]
--   p_plans: [ { slot_key, occurrence_date, chapter_id?, topic_id?, notes? } ]
--
-- `key` / `slot_key` are deterministic import group keys generated by the
-- frontend so plans can reference slots without relying on unstable array
-- indexes.
--
-- Invariants (all existing architecture is preserved — nothing is changed):
--   1. Slot identity + conflict rules are EXACTLY those of create_timetable_slot
--      (teacher/batch_subject/day/start/end with overlapping validity; teacher
--      and batch overlaps via find_timetable_slot_conflicts).
--   2. Lesson-plan semantics are EXACTLY those of upsert_lesson_plan: idempotent
--      upsert keyed on (timetable_slot_id, occurrence_date) + propagation of
--      chapter/topic to FUTURE scheduled live_classes only.
--   3. live_classes are NEVER written directly — the existing materialization
--      cron owns class generation.
--   4. The entire operation is one transaction: any validation failure raises
--      and rolls back EVERYTHING (no partial import).
--   5. History is frozen: an occurrence whose class is live/completed/already
--      started cannot be modified by bulk import.
--
-- No schema changes. No RLS changes. No existing RPC modifications.

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 1 — RPC: bulk_import_timetable
-- ════════════════════════════════════════════════════════════════════════════

create or replace function public.bulk_import_timetable(
  p_institute_id uuid,
  p_slots        jsonb,
  p_plans        jsonb,
  p_actor        uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor            uuid;
  v_timezone         text;
  v_slot             record;
  v_plan             record;
  v_batch_id         uuid;
  v_subject_id       uuid;
  v_existing_id      uuid;
  v_existing_from    date;
  v_existing_until   date;
  v_eff_from         date;
  v_eff_until        date;
  v_has_conflict     boolean;
  v_slot_id          uuid;
  v_plan_from        date;
  v_plan_until       date;
  v_slot_subject     uuid;
  v_chapter_subject  uuid;
  v_resolved_chapter uuid;
  v_plan_locked      boolean;
  v_plan_exists      boolean;
  v_occurrence_day   smallint;
  v_slots_created    integer := 0;
  v_slots_reused     integer := 0;
  v_slots_extended   integer := 0;
  v_plans_created    integer := 0;
  v_plans_updated    integer := 0;
begin
  -- ── Caller check: admins or service role (mirrors upsert_lesson_plan) ──
  if not (
    public.is_super_admin() or public.is_academic_admin()
    or auth.role() = 'service_role'
  ) then
    raise exception 'Only admins or the service role can run bulk timetable import.';
  end if;

  if p_slots is null or p_plans is null
     or jsonb_typeof(p_slots) <> 'array'
     or jsonb_typeof(p_plans) <> 'array' then
    raise exception 'p_slots and p_plans must be JSON arrays.';
  end if;

  -- V1 cap: align with the frontend importer's 5,000-row limit and prevent
  -- a huge/malicious payload from running an unbounded transaction.
  if jsonb_array_length(p_slots) > 5000
     or jsonb_array_length(p_plans) > 5000 then
    raise exception 'Bulk import supports at most 5,000 timetable slots and 5,000 lesson plans per request.';
  end if;

  -- Every element must be a JSON object (friendly errors instead of opaque
  -- jsonb_to_recordset cast failures).
  if exists (
    select 1 from jsonb_array_elements(p_slots) as e(v)
    where jsonb_typeof(v) <> 'object'
  ) or exists (
    select 1 from jsonb_array_elements(p_plans) as e(v)
    where jsonb_typeof(v) <> 'object'
  ) then
    raise exception 'Every element of p_slots and p_plans must be a JSON object.';
  end if;

  -- ── Institute binding: non-service callers must target their own institute ─
  if auth.role() <> 'service_role'
     and p_institute_id is distinct from public.get_my_institute_id() then
    raise exception 'Bulk import can only be run for your own institute.';
  end if;

  -- Resolve the institute timezone once (used for class-date mapping).
  select coalesce(timezone, 'Asia/Kolkata') into v_timezone
  from public.institutes
  where institute_id = p_institute_id;

  if v_timezone is null then
    raise exception 'Institute not found.';
  end if;

  v_actor := coalesce(p_actor, auth.uid());

  -- Transaction-local mapping: import slot key → resolved slot id.
  -- Temp tables are session-scoped and dropped at transaction end — no schema
  -- change. pg_temp is always searched first, even with an empty search_path.
  create temp table bulk_slot_map (
    key          text primary key,
    slot_id      uuid not null,
    day_of_week  smallint not null,
    valid_from   date not null,
    valid_until  date not null,
    subject_id   uuid not null
  ) on commit drop;

  -- ════════════════════════════════════════════════════════════════════════
  -- PASS 1 — Timetable slots: validate → create / reuse / extend
  -- ════════════════════════════════════════════════════════════════════════
  for v_slot in
    select * from jsonb_to_recordset(p_slots) as x(
      key text,
      teacher_id uuid,
      batch_subject_id uuid,
      day_of_week smallint,
      start_time time,
      end_time time,
      valid_from date,
      valid_until date
    )
  loop
    -- ── Structural validation ────────────────────────────────────────────
    if v_slot.key is null or v_slot.key = '' then
      raise exception 'Every timetable slot entry requires a non-empty key.';
    end if;
    if exists (select 1 from bulk_slot_map where key = v_slot.key) then
      raise exception 'Duplicate slot key % in import payload.', v_slot.key;
    end if;
    if v_slot.teacher_id is null or v_slot.batch_subject_id is null
       or v_slot.start_time is null or v_slot.end_time is null then
      raise exception 'Slot %: teacher, batch_subject, start and end times are required.', v_slot.key;
    end if;
    if v_slot.day_of_week is null or v_slot.day_of_week not between 1 and 7 then
      raise exception 'Slot %: day_of_week must be between 1 (Monday) and 7 (Sunday).', v_slot.key;
    end if;
    if v_slot.end_time <= v_slot.start_time then
      raise exception 'Slot %: end_time must be after start_time.', v_slot.key;
    end if;
    if v_slot.valid_from is null or v_slot.valid_until is null
       or v_slot.valid_until < v_slot.valid_from then
      raise exception 'Slot %: valid_from and valid_until are required and valid_until must be on or after valid_from.', v_slot.key;
    end if;

    -- ── The batch_subject must belong to this institute ──────────────────
    select bs.batch_id, bs.subject_id into v_batch_id, v_subject_id
    from public.batch_subjects bs
    where bs.batch_subject_id = v_slot.batch_subject_id
      and bs.institute_id = p_institute_id;

    if v_batch_id is null then
      raise exception 'Slot %: the selected batch-subject does not belong to this institute.', v_slot.key;
    end if;

    -- ── Teacher must be assigned to the batch-subject ────────────────────
    -- Authoritative model: batch_subject_teachers (never batch_teachers).
    if not exists (
      select 1 from public.batch_subject_teachers bst
      where bst.batch_subject_id = v_slot.batch_subject_id
        and bst.teacher_id = v_slot.teacher_id
        and bst.institute_id = p_institute_id
    ) then
      raise exception 'Slot %: the selected teacher is not assigned to this batch-subject.', v_slot.key;
    end if;

    -- ── Serialize concurrent imports/creates for this teacher-day / batch-day ─
    perform pg_advisory_xact_lock(
      hashtextextended(
        p_institute_id::text || ':' || v_slot.teacher_id::text || ':' || v_slot.day_of_week::text,
        0
      )
    );
    perform pg_advisory_xact_lock(
      hashtextextended(
        p_institute_id::text || ':' || v_batch_id::text || ':' || v_slot.day_of_week::text,
        0
      )
    );

    -- ── Try to REUSE an existing overlapping slot with the identical schedule ─
    select t.timetable_slot_id, t.valid_from, t.valid_until
      into v_existing_id, v_existing_from, v_existing_until
    from public.timetable_slots t
    where t.institute_id = p_institute_id
      and t.teacher_id = v_slot.teacher_id
      and t.batch_subject_id = v_slot.batch_subject_id
      and t.day_of_week = v_slot.day_of_week
      and t.start_time = v_slot.start_time
      and t.end_time = v_slot.end_time
      and t.status in (
        'active'::public.timetable_slot_status,
        'paused'::public.timetable_slot_status
      )
      and daterange(t.valid_from, t.valid_until, '[]')
          && daterange(v_slot.valid_from, v_slot.valid_until, '[]')
    order by t.valid_from asc
    limit 1;

    if v_existing_id is not null then
      -- REUSE — never create a duplicate slot.
      v_slots_reused := v_slots_reused + 1;
      v_slot_id := v_existing_id;

      -- Effective validity = existing window ∪ import window (overlap is
      -- guaranteed by the reuse query). If the union differs from the existing
      -- window, extend it safely — re-running the authoritative conflict check
      -- for the new window, excluding the slot being extended.
      v_eff_from  := least(v_slot.valid_from, v_existing_from);
      v_eff_until := greatest(v_slot.valid_until, v_existing_until);

      if v_eff_from <> v_existing_from or v_eff_until <> v_existing_until then
        select exists(
          select 1 from public.find_timetable_slot_conflicts(
            p_institute_id, v_slot.teacher_id, v_slot.batch_subject_id,
            v_slot.day_of_week, v_slot.start_time, v_slot.end_time,
            v_eff_from, v_eff_until, v_existing_id
          )
        ) into v_has_conflict;

        if v_has_conflict then
          raise exception 'Slot %: extending the existing timetable slot would conflict with another slot on this day/time.', v_slot.key;
        end if;

        update public.timetable_slots
        set valid_from  = v_eff_from,
            valid_until = v_eff_until,
            updated_by  = v_actor,
            updated_at  = now()
        where timetable_slot_id = v_existing_id;

        v_slots_extended := v_slots_extended + 1;
      end if;
    else
      -- CREATE — authoritative conflict check (a stale frontend preview can
      -- never slip through: another admin's create is caught here).
      select exists(
        select 1 from public.find_timetable_slot_conflicts(
          p_institute_id, v_slot.teacher_id, v_slot.batch_subject_id,
          v_slot.day_of_week, v_slot.start_time, v_slot.end_time,
          v_slot.valid_from, v_slot.valid_until, null
        )
      ) into v_has_conflict;

      if v_has_conflict then
        raise exception 'Slot %: the same teacher or batch already has an active slot on this day/time within an overlapping validity window.', v_slot.key;
      end if;

      insert into public.timetable_slots (
        institute_id, teacher_id, batch_subject_id,
        day_of_week, start_time, end_time, valid_from, valid_until,
        status, created_by
      )
      values (
        p_institute_id, v_slot.teacher_id, v_slot.batch_subject_id,
        v_slot.day_of_week, v_slot.start_time, v_slot.end_time,
        v_slot.valid_from, v_slot.valid_until,
        'active'::public.timetable_slot_status, v_actor
      )
      returning timetable_slot_id into v_slot_id;

      v_slots_created := v_slots_created + 1;
      v_eff_from  := v_slot.valid_from;
      v_eff_until := v_slot.valid_until;
    end if;

    -- Store the slot's FINAL validity (post-extension when applicable) so plan
    -- validation always matches the real slot window — even when the admin
    -- supplied an explicit Valid From/Until wider than the file's dates.
    insert into bulk_slot_map (key, slot_id, day_of_week, valid_from, valid_until, subject_id)
    values (
      v_slot.key, v_slot_id, v_slot.day_of_week,
      v_eff_from, v_eff_until, v_subject_id
    );
  end loop;

  -- ════════════════════════════════════════════════════════════════════════
  -- PASS 2 — Lesson plans: validate → upsert via the existing RPC
  -- ════════════════════════════════════════════════════════════════════════
  for v_plan in
    select * from jsonb_to_recordset(p_plans) as x(
      slot_key text,
      occurrence_date date,
      chapter_id uuid,
      topic_id uuid,
      notes text
    )
  loop
    select m.slot_id, m.day_of_week, m.valid_from, m.valid_until, m.subject_id
      into v_slot_id, v_occurrence_day, v_plan_from, v_plan_until, v_slot_subject
    from bulk_slot_map m
    where m.key = v_plan.slot_key;

    if v_slot_id is null then
      raise exception 'Lesson plan for % references an unknown timetable slot key.', coalesce(v_plan.slot_key, '?');
    end if;
    if v_plan.occurrence_date is null then
      raise exception 'Lesson plan for slot % is missing an occurrence date.', v_plan.slot_key;
    end if;

    -- ── Occurrence must match the slot's weekday ──────────────────────────
    if (extract(isodow from v_plan.occurrence_date))::smallint <> v_occurrence_day then
      raise exception 'Occurrence % does not fall on the timetable slot''s day of week.', v_plan.occurrence_date;
    end if;

    -- ── Occurrence must be within the slot's validity ─────────────────────
    if v_plan.occurrence_date < v_plan_from or v_plan.occurrence_date > v_plan_until then
      raise exception 'Occurrence % is outside the timetable slot''s validity period.', v_plan.occurrence_date;
    end if;

    -- ── History is frozen: live/completed/already-started classes ─────────
    -- are never silently rewritten by bulk import. Cancelled/draft classes are
    -- deliberately NOT locked: the plan row is a recorded intent, and class
    -- data is never touched because propagation only updates status='scheduled'
    -- rows that are still in the future.
    select exists(
      select 1 from public.live_classes lc
      where lc.timetable_slot_id = v_slot_id
        and (lc.scheduled_at at time zone v_timezone)::date = v_plan.occurrence_date
        and (
          lc.status in (
            'live'::public.live_class_status,
            'completed'::public.live_class_status
          )
          or (
            lc.status = 'scheduled'::public.live_class_status
            and lc.scheduled_at <= now()
          )
        )
    ) into v_plan_locked;

    if v_plan_locked then
      raise exception 'Occurrence % already has a class that has started or completed; historical occurrences cannot be modified by bulk import.', v_plan.occurrence_date;
    end if;

    -- ── Resolve the chapter (explicit, or derived from a topic-only row) ──
    v_resolved_chapter := v_plan.chapter_id;
    if v_resolved_chapter is null and v_plan.topic_id is not null then
      select chapter_id into v_resolved_chapter
      from public.topics
      where topic_id = v_plan.topic_id;

      if v_resolved_chapter is null then
        raise exception 'Topic % does not exist.', v_plan.topic_id;
      end if;
    end if;

    -- ── Chapter must belong to the slot's subject ─────────────────────────
    -- (the existing upsert_lesson_plan validates topic→chapter only, so this
    -- subject check is the bulk RPC's own defense in depth)
    if v_resolved_chapter is not null then
      select subject_id into v_chapter_subject
      from public.chapters
      where chapter_id = v_resolved_chapter;

      if v_chapter_subject is null then
        raise exception 'Chapter % does not exist.', v_resolved_chapter;
      end if;
      if v_chapter_subject is distinct from v_slot_subject then
        raise exception 'Chapter % does not belong to the subject of this timetable slot.', v_resolved_chapter;
      end if;
    end if;

    -- ── Topic must belong to the resolved chapter (chapter-only is valid) ─
    if v_plan.topic_id is not null then
      if not exists (
        select 1 from public.topics t
        where t.topic_id = v_plan.topic_id
          and t.chapter_id = v_resolved_chapter
      ) then
        raise exception 'Topic % does not belong to the selected chapter.', v_plan.topic_id;
      end if;
    end if;

    -- ── Count created vs updated before delegating the upsert ─────────────
    select exists(
      select 1 from public.lesson_plans lp
      where lp.timetable_slot_id = v_slot_id
        and lp.occurrence_date = v_plan.occurrence_date
    ) into v_plan_exists;

    -- ── Reuse the existing single-plan RPC: idempotent upsert + propagation
    -- to future scheduled classes only. No live_classes writes here.
    perform public.upsert_lesson_plan(
      v_slot_id,
      v_plan.occurrence_date,
      v_resolved_chapter,
      v_plan.topic_id,
      v_plan.notes,
      v_actor
    );

    if v_plan_exists then
      v_plans_updated := v_plans_updated + 1;
    else
      v_plans_created := v_plans_created + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'success', true,
    'slotsCreated',  v_slots_created,
    'slotsReused',   v_slots_reused,
    'slotsExtended', v_slots_extended,
    'plansCreated',  v_plans_created,
    'plansUpdated',  v_plans_updated
  );
end;
$$;

comment on function public.bulk_import_timetable(uuid, jsonb, jsonb, uuid) is
  'Atomic bulk import of timetable slots + lesson plans. SECURITY DEFINER, '
  'admin/service-role only, bound to the caller''s own institute. Slot identity '
  'reuses create_timetable_slot semantics (teacher/batch_subject/day/start/end '
  'with overlapping validity — reuse, extend, or create), lesson plans reuse '
  'upsert_lesson_plan semantics (idempotent upsert + propagation to future '
  'scheduled classes only). Never writes live_classes directly. Any invalid '
  'row rolls back the entire transaction. Returns '
  '{success, slotsCreated, slotsReused, slotsExtended, plansCreated, plansUpdated}.';

-- ── Privileges: deny public, grant authenticated + service_role ────────────
-- The function enforces admin role + institute scope internally (matching the
-- create_timetable_slot / upsert_lesson_plan pattern), so authenticated
-- teachers and students can call it but always receive a raised exception.
revoke all on function public.bulk_import_timetable(uuid, jsonb, jsonb, uuid) from public;

grant execute on function public.bulk_import_timetable(uuid, jsonb, jsonb, uuid)
  to authenticated, service_role;

-- ════════════════════════════════════════════════════════════════════════════
-- END OF MIGRATION — 114 Bulk Timetable + Lesson Plan Import
-- ════════════════════════════════════════════════════════════════════════════
