-- ============================================================================
-- Migration: 119 — Single-Device Login Foundation (Phase S1)
--
-- PostgreSQL 16 | Supabase Compatible | Production Ready
--
-- Scope: DATABASE-ONLY foundation for "ONE USER ACCOUNT = ONE ACTIVE APP
--        INSTALLATION" in the student mobile app. This migration is fully
--        additive: no existing table is modified, no data is backfilled,
--        and migrations 117 / 118 (Doubt System) are NOT touched.
--
-- Design summary (verified against the live repository):
--   • Dedicated public.user_device_sessions table. device_tokens is NOT
--     overloaded — it remains the canonical FCM push-token table.
--   • device_installation_id is a TEXT identifier GENERATED BY THE MOBILE
--     APP (a crypto-random UUID via react-native-get-random-values, Phase
--     S2). It is NOT generated here, and is NEVER an IMEI / hardware serial.
--   • ONE ACTIVE DEVICE PER PROFILE is guaranteed at the DATABASE level by
--     a partial unique index:
--         create unique index ... on user_device_sessions (profile_id)
--         where is_active = true;
--     Application code cannot race around this — PostgreSQL refuses to
--     create a second active row.
--   • All sensitive state transitions (activation / replacement / logout)
--     happen ONLY through SECURITY DEFINER RPCs. RLS provides SELECT for
--     the owner only and NO direct INSERT/UPDATE/DELETE policies, so a
--     client can never flip is_active itself.
--   • Identity is derived EXCLUSIVELY from auth.uid() inside the RPCs.
--     No profile_id / user_id / institute_id is ever accepted from the
--     client for authorization.
--   • Concurrency: pg_advisory_xact_lock(hashtext(profile)) serializes
--     concurrent registrations; the partial unique index is the final
--     database safety net.
--   • Realtime: the table is added to the supabase_realtime publication
--     (idempotent, guarded) so the mobile app can subscribe to
--     postgres_changes later (Phase S4). The mobile subscription itself
--     is NOT implemented here.
--
-- Reference: Phase S1 analysis report (single-device login architecture)
-- ============================================================================

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 1 — CREATE TABLE: user_device_sessions
-- ════════════════════════════════════════════════════════════════════════════
-- One row per (profile, app installation). An installation is identified by
-- the app-generated device_installation_id; the row carries lifecycle state
-- (is_active / activated_at / last_seen_at / revoked_at / revoked_reason)
-- plus optional metadata (fcm_token, platform, device_name, app_version).
-- fcm_token here is INFORMATIONAL only — device_tokens remains the canonical
-- push-token table.

create table if not exists public.user_device_sessions (
  -- Primary Key (surrogate UUID)
  session_device_id     uuid                  not null  default gen_random_uuid(),

  -- Owning profile (1:1 with auth.users.id via public.profiles)
  profile_id            uuid                  not null,

  -- App-generated installation identifier (crypto-random UUID from Phase S2).
  -- NEVER an IMEI / serial number. NULL is not allowed.
  device_installation_id text                 not null,

  -- Informational FCM token metadata (canonical source: device_tokens)
  fcm_token             text                  null      default null,

  -- Device platform; nullable (client may omit), constrained when present
  platform              text                  null      default null,

  -- Optional human-readable device name (e.g. "Samsung Galaxy S24")
  device_name           text                  null      default null,

  -- App version at registration time
  app_version           text                  null      default null,

  -- Whether this installation is currently THE active device for the profile
  is_active             boolean               not null  default false,

  -- When this installation became (or most recently became) active
  activated_at          timestamptz           null      default null,

  -- Last time this installation contacted the server (heartbeat / validation)
  last_seen_at          timestamptz           null      default null,

  -- When the device was revoked / deactivated. NULL while active or fresh.
  revoked_at            timestamptz           null      default null,

  -- Why it was revoked: 'replaced_by_new_device' | 'user_logout'
  revoked_reason        text                  null      default null,

  -- Audit fields
  created_at            timestamptz           not null  default now(),
  updated_at            timestamptz           not null  default now(),

  -- ── Primary Key ───────────────────────────────────────────────────────
  constraint pk_user_device_sessions primary key (session_device_id),

  -- ── Foreign Keys ──────────────────────────────────────────────────────
  -- FK to profiles: the owner of this device session. CASCADE so a profile
  -- deletion removes its device rows (auth.user lifecycle).
  constraint fk_user_device_sessions_profile
    foreign key (profile_id) references public.profiles (profile_id)
    on delete cascade
    on update restrict,

  -- ── Unique Constraints ────────────────────────────────────────────────
  -- One row per (profile, installation) — re-registering the SAME
  -- installation (e.g. login again on the same phone) must UPSERT, never
  -- duplicate. Also backs the profile+installation lookup index.
  constraint uq_user_device_sessions_profile_install
    unique (profile_id, device_installation_id),

  -- ── CHECK Constraints ─────────────────────────────────────────────────
  -- Platform sanity (mirrors ck_device_tokens_platform from migration 048)
  constraint ck_user_device_sessions_platform check (
    platform is null or platform in ('android', 'ios')
  ),

  -- Active-state consistency:
  --   is_active = true  ⇒ activated_at IS NOT NULL AND no revocation fields
  --   is_active = false ⇒ any inactive representation is acceptable
  -- This prevents "active with no activation timestamp" or "active while
  -- revoked" half-states without blocking legitimate lifecycle transitions.
  constraint ck_user_device_sessions_active_consistency check (
    (is_active = true
       and activated_at is not null
       and revoked_at is null
       and revoked_reason is null)
    or (is_active = false)
  ),

  -- Revocation fields travel together
  constraint ck_user_device_sessions_revocation check (
    (revoked_at is null and revoked_reason is null)
    or (revoked_at is not null and revoked_reason is not null)
  ),

  -- Allowed revocation reasons (extend additively in a later migration if a
  -- new reason is ever required)
  constraint ck_user_device_sessions_revoked_reason check (
    revoked_reason is null
    or revoked_reason in ('replaced_by_new_device', 'user_logout')
  ),

  -- Installation id hygiene: non-empty, sane length (UUID = 36 chars)
  constraint ck_user_device_sessions_install_id check (
    char_length(trim(device_installation_id)) between 8 and 128
  )
);

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 2 — THE SINGLE-ACTIVE-DEVICE GUARANTEE (partial unique index)
-- ════════════════════════════════════════════════════════════════════════════
-- This is the database-level guarantee: at most ONE active row per profile.
-- Even if two phones log in simultaneously (or a malicious client bypasses
-- the RPCs entirely), PostgreSQL refuses to store a second active row —
-- the INSERT / UPDATE fails with a unique violation (23505). Application
-- sequencing alone is NEVER sufficient; this index is the authority.
create unique index if not exists uq_user_device_sessions_single_active
  on public.user_device_sessions (profile_id)
  where is_active;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 3 — Triggers
-- ════════════════════════════════════════════════════════════════════════════
-- updated_at maintenance (uses set_updated_at() from migration 002).
-- No lifecycle trigger is needed — state transitions are enforced by the
-- RPCs + the partial unique index above, mirroring the trusted_devices
-- decision to keep single-active rules in the RPC/index layer.
drop trigger if exists trg_user_device_sessions_set_updated_at
  on public.user_device_sessions;

create trigger trg_user_device_sessions_set_updated_at
  before update on public.user_device_sessions
  for each row
  execute function public.set_updated_at();

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 4 — Row-Level Security
-- ════════════════════════════════════════════════════════════════════════════

alter table public.user_device_sessions enable row level security;

-- 4a. Device owner: SELECT ONLY their own rows.
--     Users may read their own device sessions (e.g. a future "devices"
--     screen) and — critically — this policy is what allows the mobile app
--     to subscribe to Realtime postgres_changes scoped to their own rows in
--     Phase S4.
--     There are deliberately NO INSERT / UPDATE / DELETE policies: every
--     write must go through the SECURITY DEFINER RPCs below. Without an
--     UPDATE policy a client cannot flip is_active / revoked_at /
--     revoked_reason / activated_at directly, and without an INSERT policy
--     it cannot fabricate rows. This is the RLS half of "no direct state
--     tampering".
drop policy if exists "Device owners can read their own device sessions"
  on public.user_device_sessions;

create policy "Device owners can read their own device sessions"
  on public.user_device_sessions
  for select
  to authenticated
  using (profile_id = auth.uid());

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 5 — Realtime (database-side only; client subscription is Phase S4)
-- ════════════════════════════════════════════════════════════════════════════
-- Add the table to the supabase_realtime publication so postgres_changes
-- events fire for it. Guarded + idempotent: on stacks where the publication
-- does not exist (e.g. Realtime disabled), this is a safe no-op; where it
-- exists, the table is added exactly once. The mobile client (Phase S4) will
-- subscribe with a filter on its own profile_id, which is permitted by the
-- SELECT policy above.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
         from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'user_device_sessions'
     ) then
    alter publication supabase_realtime add table public.user_device_sessions;
  end if;
end $$;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 6 — RPC: register_active_device()
-- ════════════════════════════════════════════════════════════════════════════
-- The ONLY way to (re)activate an installation for the authenticated user.
--
-- Behaviour:
--   1. Requires auth.uid() (never accepts a client-supplied profile id).
--   2. Serializes per-profile via pg_advisory_xact_lock(hashtext(profile)).
--   3. Revokes any OTHER currently-active installation for this profile
--      (revoked_reason = 'replaced_by_new_device').
--   4. UPSERTs the current installation as active — logging in again on
--      the SAME installation re-activates its existing row (no duplicate).
--   5. Audits via write_audit_log ('create' for a new install, 'update'
--      for re-activation of an existing install).
--   6. Returns a jsonb envelope:
--        { success, installedDeviceId, isNewInstall, revokedPreviousDeviceIds }
--
-- Concurrency: the advisory lock serializes concurrent logins for the same
-- profile; the partial unique index (Section 2) is the final safety net —
-- if a race somehow slipped through, one of the two transactions fails with
-- a unique violation instead of creating two active rows.

create or replace function public.register_active_device(
  p_installation_id text,
  p_platform        text default null,
  p_device_name     text default null,
  p_app_version     text default null,
  p_fcm_token       text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile_id   uuid;
  v_session_id   uuid;
  v_was_existing boolean;
  v_revoked      uuid[] := '{}';
  v_revoked_id   uuid;
  v_action       public.audit_action_type;
begin
  -- ── 1. Identity comes ONLY from auth.uid() (role check for parity with
  --        the migration-118 RPC family — anon never has a uid, but the
  --        explicit authenticated check is the project convention) ──────
  if auth.role() <> 'authenticated' then
    return jsonb_build_object('success', false, 'error', 'Not authenticated.');
  end if;
  v_profile_id := auth.uid();
  if v_profile_id is null then
    return jsonb_build_object('success', false, 'error', 'Not authenticated.');
  end if;

  -- ── 2. Validate the installation id (client supplies identity, not auth) ─
  if p_installation_id is null
     or char_length(trim(p_installation_id)) < 8
     or char_length(trim(p_installation_id)) > 128 then
    return jsonb_build_object(
      'success', false,
      'error', 'A valid device installation id is required.'
    );
  end if;
  p_installation_id := trim(p_installation_id);

  -- ── 2b. Validate platform up-front for a clean error envelope (the column
  --        CHECK is the authoritative backstop) ───────────────────────────
  if p_platform is not null and p_platform not in ('android', 'ios') then
    return jsonb_build_object(
      'success', false,
      'error', 'Platform must be android, ios, or null.'
    );
  end if;

  -- ── 3. Serialize concurrent registrations for this profile ──────────────
  perform pg_advisory_xact_lock(
    hashtext('user_device_sessions::' || v_profile_id::text)
  );

  -- ── 4. Was this installation already registered? (audit action choice) ──
  select exists (
    select 1 from public.user_device_sessions
     where profile_id = v_profile_id
       and device_installation_id = p_installation_id
  ) into v_was_existing;

  -- ── 5. Revoke ANY OTHER active installation for this profile ────────────
  for v_revoked_id in
    update public.user_device_sessions
       set is_active      = false,
           revoked_at     = now(),
           revoked_reason = 'replaced_by_new_device'
     where profile_id     = v_profile_id
       and is_active
       and device_installation_id <> p_installation_id
     returning session_device_id
  loop
    v_revoked := array_append(v_revoked, v_revoked_id);
  end loop;

  -- ── 6. Upsert THIS installation as the active device ────────────────────
  insert into public.user_device_sessions (
    profile_id,
    device_installation_id,
    fcm_token,
    platform,
    device_name,
    app_version,
    is_active,
    activated_at,
    last_seen_at
  )
  values (
    v_profile_id,
    p_installation_id,
    p_fcm_token,
    p_platform,
    p_device_name,
    p_app_version,
    true,
    now(),
    now()
  )
  on conflict (profile_id, device_installation_id)
  do update set
    fcm_token      = excluded.fcm_token,
    platform       = excluded.platform,
    device_name    = excluded.device_name,
    app_version    = excluded.app_version,
    is_active      = true,
    -- Re-activation: keep the original activation timestamp
    activated_at   = coalesce(public.user_device_sessions.activated_at, now()),
    last_seen_at   = now(),
    revoked_at     = null,
    revoked_reason = null
  returning session_device_id into v_session_id;

  -- ── 7. Audit (same transaction) ──────────────────────────────────────────
  v_action := case
    when v_was_existing then 'update'::public.audit_action_type
    else 'create'::public.audit_action_type
  end;

  perform public.write_audit_log(
    v_action,
    'user_device_session',
    v_session_id,
    null,
    jsonb_build_object(
      'device_installation_id', p_installation_id,
      'platform',               p_platform,
      'is_active',              true,
      'activated_at',           now()
    ),
    jsonb_build_object(
      'context',   'register_active_device',
      'version',   '119',
      'revoked_previous_count', coalesce(cardinality(v_revoked), 0)
    )
  );

  -- ── 8. Return ────────────────────────────────────────────────────────────
  return jsonb_build_object(
    'success',                  true,
    'installedDeviceId',        v_session_id::text,
    'isNewInstall',             not v_was_existing,
    'revokedPreviousDeviceIds', to_jsonb(v_revoked)
  );
end;
$$;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 7 — RPC: validate_active_device()
-- ════════════════════════════════════════════════════════════════════════════
-- Cheap, read-only, side-effect-free check used by the mobile app at
-- startup / foreground / reconnect: "is MY installation still the active
-- one?" Returns { active: true | false }. Never raises; never writes;
-- safe to call repeatedly (single indexed lookup). Identity is derived
-- from auth.uid() — the caller can only ever validate their OWN device.

create or replace function public.validate_active_device(
  p_installation_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile_id uuid;
  v_active     boolean;
begin
  -- Read-only validation: never raises; unauthenticated / anon → inactive.
  if auth.role() <> 'authenticated' then
    return jsonb_build_object('active', false);
  end if;
  v_profile_id := auth.uid();
  if v_profile_id is null then
    return jsonb_build_object('active', false);
  end if;

  if p_installation_id is null or trim(p_installation_id) = '' then
    return jsonb_build_object('active', false);
  end if;

  select exists (
    select 1 from public.user_device_sessions
     where profile_id = v_profile_id
       and device_installation_id = trim(p_installation_id)
       and is_active
  ) into v_active;

  return jsonb_build_object('active', coalesce(v_active, false));
end;
$$;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 8 — RPC: deactivate_active_device()
-- ════════════════════════════════════════════════════════════════════════════
-- Called by the mobile app on intentional logout. Marks ONLY the caller's
-- own installation inactive (revoked_reason = 'user_logout'). Profile is
-- derived from auth.uid() — a client can NEVER deactivate another user's
-- device, even if it knows that user's installation id.

create or replace function public.deactivate_active_device(
  p_installation_id text,
  p_reason          text default 'user_logout'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile_id uuid;
  v_session_id uuid;
begin
  -- ── 1. Identity comes ONLY from auth.uid() (role check for parity with
  --        the migration-118 RPC family) ──────────────────────────────────
  if auth.role() <> 'authenticated' then
    return jsonb_build_object('success', false, 'error', 'Not authenticated.');
  end if;
  v_profile_id := auth.uid();
  if v_profile_id is null then
    return jsonb_build_object('success', false, 'error', 'Not authenticated.');
  end if;

  -- ── 2. Validate inputs ───────────────────────────────────────────────────
  if p_installation_id is null or trim(p_installation_id) = '' then
    return jsonb_build_object(
      'success', false,
      'error', 'A valid device installation id is required.'
    );
  end if;
  p_installation_id := trim(p_installation_id);

  -- This RPC is the CLIENT-initiated logout path, so only the explicit
  -- logout reason is accepted here. 'replaced_by_new_device' is a
  -- server-side reason set only by register_active_device() (the DB CHECK
  -- keeps the full list for future server-side flows).
  if p_reason is null or p_reason <> 'user_logout' then
    return jsonb_build_object(
      'success', false,
      'error', 'Only user_logout is supported for client deactivation.'
    );
  end if;

  -- ── 3. Deactivate ONLY the caller's own active installation ─────────────
  update public.user_device_sessions
     set is_active      = false,
         revoked_at     = now(),
         revoked_reason = p_reason,
         last_seen_at   = now()
   where profile_id     = v_profile_id
     and device_installation_id = p_installation_id
     and is_active
   returning session_device_id into v_session_id;

  if v_session_id is null then
    return jsonb_build_object(
      'success', false,
      'error', 'No active device found for this installation.'
    );
  end if;

  -- ── 4. Audit (same transaction; logout action carries no new_value) ─────
  perform public.write_audit_log(
    'logout'::public.audit_action_type,
    'user_device_session',
    v_session_id,
    jsonb_build_object('is_active', true),
    null,
    jsonb_build_object(
      'context', 'deactivate_active_device',
      'version', '119',
      'reason',  p_reason
    )
  );

  -- ── 5. Return ────────────────────────────────────────────────────────────
  return jsonb_build_object(
    'success',            true,
    'deactivatedDeviceId', v_session_id::text
  );
end;
$$;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 9 — Execution grants (defense in depth)
-- ════════════════════════════════════════════════════════════════════════════
-- All three RPCs are SECURITY DEFINER and internally derive identity from
-- auth.uid(), so restricting EXECUTE to authenticated (+ service_role for
-- future server-side flows) is safe: an authenticated caller can only ever
-- operate on their OWN device sessions. The public/anon role gets nothing.

revoke execute on function public.register_active_device(text, text, text, text, text) from public;
revoke execute on function public.validate_active_device(text) from public;
revoke execute on function public.deactivate_active_device(text, text) from public;

grant execute on function public.register_active_device(text, text, text, text, text) to authenticated, service_role;
grant execute on function public.validate_active_device(text) to authenticated, service_role;
grant execute on function public.deactivate_active_device(text, text) to authenticated, service_role;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 10 — COMMENT Statements
-- ════════════════════════════════════════════════════════════════════════════

comment on table public.user_device_sessions is
  'Single-device-login foundation (Phase S1). One row per (profile, app '
  'installation). The partial unique index uq_user_device_sessions_single_active '
  'guarantees at most ONE active device per profile at the database level. '
  'All state transitions occur through SECURITY DEFINER RPCs '
  '(register_active_device / validate_active_device / deactivate_active_device); '
  'RLS is SELECT-only for the owner, so clients cannot flip is_active directly. '
  'device_installation_id is generated by the mobile app (never an IMEI/serial). '
  'fcm_token here is informational — device_tokens remains canonical.';

comment on column public.user_device_sessions.session_device_id is
  'Surrogate primary key for this device-session row.';

comment on column public.user_device_sessions.profile_id is
  'FK to public.profiles (1:1 with auth.users.id). Derived from auth.uid() '
  'inside the RPCs — never accepted from the client.';

comment on column public.user_device_sessions.device_installation_id is
  'App-generated installation identifier (crypto-random UUID from Phase S2). '
  'Identifies a single app installation; regenerates on reinstall / data '
  'clear, which correctly treats a fresh install as a new device.';

comment on column public.user_device_sessions.fcm_token is
  'Informational copy of the FCM push token for this installation. The '
  'canonical push-token table remains public.device_tokens — this column '
  'exists only for convenient device-session context.';

comment on column public.user_device_sessions.platform is
  'Device platform: android or ios (nullable when the client omits it).';

comment on column public.user_device_sessions.device_name is
  'Optional human-readable device name (e.g. "Samsung Galaxy S24").';

comment on column public.user_device_sessions.app_version is
  'App version at registration time.';

comment on column public.user_device_sessions.is_active is
  'Whether this installation is currently THE active device for the profile. '
  'Enforced single-active by the partial unique index '
  'uq_user_device_sessions_single_active. Never writable directly by clients.';

comment on column public.user_device_sessions.activated_at is
  'When this installation became (or most recently became) active. NULL '
  'until the first activation.';

comment on column public.user_device_sessions.last_seen_at is
  'Last time this installation contacted the server. Updated on registration '
  'and on deactivation.';

comment on column public.user_device_sessions.revoked_at is
  'When this device was revoked / deactivated. NULL while active or fresh. '
  'Travels with revoked_reason (see ck_user_device_sessions_revocation).';

comment on column public.user_device_sessions.revoked_reason is
  'Why the device was revoked: replaced_by_new_device (a newer login took '
  'over) or user_logout (intentional sign-out).';

comment on function public.register_active_device(text, text, text, text, text) is
  'SECURITY DEFINER. Activates the caller''s installation as the single '
  'active device for auth.uid(), atomically revoking any other active '
  'installation (revoked_reason = replaced_by_new_device). Re-login on the '
  'same installation re-activates its existing row. Serialized by '
  'pg_advisory_xact_lock(hashtext(profile)); the partial unique index is the '
  'final concurrency safety net. Identity derives from auth.uid() only. '
  'Returns { success, installedDeviceId, isNewInstall, revokedPreviousDeviceIds } '
  'or { success: false, error }.';

comment on function public.validate_active_device(text) is
  'SECURITY DEFINER, read-only. Returns { active: true } if the caller''s '
  'installation (auth.uid() + p_installation_id) is the currently active '
  'device, otherwise { active: false }. Safe to call repeatedly — single '
  'indexed lookup, no writes. Used by the mobile app at startup / foreground '
  '/ reconnect (Phase S4).';

comment on function public.deactivate_active_device(text, text) is
  'SECURITY DEFINER. Marks the caller''s OWN active installation inactive '
  '(revoked_reason = user_logout). Profile derives from auth.uid() — a '
  'client can never deactivate another user''s device. Only user_logout is '
  'accepted from the client; replaced_by_new_device is server-side only '
  '(set by register_active_device). Returns { success: true, '
  'deactivatedDeviceId } or { success: false, error }.';

-- ════════════════════════════════════════════════════════════════════════════
-- END OF MIGRATION — 119 Single-Device Login Foundation
-- ════════════════════════════════════════════════════════════════════════════
